### ISSUE TITLE
brave browser wallet rendering and characters messed up

### ISSUE THREAD

**Issue by ccgarant** [berry-pool/nami#484]
Nami wallet characters for LP tokens and rendering is messed up using Brave Browser: [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (x86_64)] (See attached photo)
- Total Amount overlaps with something else, overlapping hard to read
- The tokens button overlaps and hidden by receive button
- The LP token characters come up as gibberish wingdings.

![Screen Shot 2022-03-26 at 1 48 54 PM](https://user-images.githubusercontent.com/25705528/160251385-94303e9e-6858-4502-9cd1-7e49f19c9dc2.png)

**Comment by alessandrokonrad** [comment]
You must have changed your overall zoom settings in brave. Try to set it to the default 100% and Nami should look fine.

Regarding the messed up characters, these are assets which use a hex encoded name. I could try to change the weird symbols to a string of numbers, but it doesn't make it human readable either.
