### ISSUE TITLE
Vasil branch: Unable to use signData with StakeAddress

### ISSUE THREAD

**Issue by georgeos** [berry-pool/nami#673]
Using vasil branch, I'm not able to use the `signData` endpoint with a Stake address. Error received is:
```
{
    "code": 1,
    "info": "Wallet could not sign the data (e.g. does not have the secret key associated with the address)."
}
```
Which is related to: `DataSignError.ProofGeneration`

Is it necessary to change something when calling this endpoint? Using the current version (3.2.5) works fine.

**Comment by AdorchaDev** [comment]
Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

**Comment by georgeos** [comment]
> Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

What?

**Comment by hazryder** [comment]
@georgeos Ignore the message from @AdorchaDev, it’s a phishing scam they’ve been running on here for ages, they reply to every issue with it.

**Comment by alessandrokonrad** [comment]
> Using vasil branch, I'm not able to use the `signData` endpoint with a Stake address. Error received is:
> 
> ```
> {
>     "code": 1,
>     "info": "Wallet could not sign the data (e.g. does not have the secret key associated with the address)."
> }
> ```
> 
> Which is related to: `DataSignError.ProofGeneration`
> 
> Is it necessary to change something when calling this endpoint? Using the current version (3.2.5) works fine.

Hey @georgeos it looks like you use an address that is not associated with the wallet/account. Do you try this on mainnet, or what network are you using?

**Comment by georgeos** [comment]
> Hey @georgeos it looks like you use an address that is not associated with the wallet/account. Do you try this on mainnet, or what network are you using?

Thanks for your answer. I already tried in mainnet, preprod and preview networks. To sign the data, I'm using the same process that we've in production now, using Nami 3.2.5.

**Comment by alessandrokonrad** [comment]
> > Hey @georgeos it looks like you use an address that is not associated with the wallet/account. Do you try this on mainnet, or what network are you using?
> 
> Thanks for your answer. I already tried in mainnet, preprod and preview networks. To sign the data, I'm using the same process that we've in production now, using Nami 3.2.5.

There was indeed a little issue. I hope it is resolved now, let me know how it goes. Note I have everything in the main branch now. There is also the link to the current custom build in the readme.

**Comment by hazryder** [comment]
Retested with the new build against the Preview network, the signing issue is resolved on my end :)

**Comment by georgeos** [comment]
> There was indeed a little issue. I hope it is resolved now, let me know how it goes. Note I have everything in the main branch now. There is also the link to the current custom build in the readme.

Confirmed, it's working now! Thanks for your help!
