### ISSUE TITLE
Vasil branch: Collateral not working properly

### ISSUE THREAD

**Issue by carleryd** [berry-pool/nami#675]
I'm using the [latest build off the vasil branch](https://github.com/berry-pool/nami/commit/01b88ace7b264c9b54d123eeb3dc11609e380ce7)

I'm trying to use Nami on the pre-prod testnet and thing seem to work fine before I set a collateral

<img width="675" alt="Screenshot 2022-09-09 at 17 37 30" src="https://user-images.githubusercontent.com/3730014/189399066-efb623ec-d10b-4e52-bf08-794d97dd2d49.png">

however after I set a collateral the function errors out

<img width="543" alt="Screenshot 2022-09-09 at 17 38 50" src="https://user-images.githubusercontent.com/3730014/189399323-15f4dfdb-318a-4c02-a602-db400816c06b.png">

I tried with an imported wallet and also a newly created wallet, both have the same issue.

**Comment by nmaddp1995** [comment]
Maybe it's similar with my issue https://github.com/berry-pool/nami/issues/674
Hope they can answer soon

**Comment by alessandrokonrad** [comment]
@carleryd @nmaddp1995 this should be resolved now on the vasil branch.

**Comment by carleryd** [comment]
Thank you @alessandrokonrad , I can confirm the latest build resolves this issue 🥳 
Using this build https://github.com/berry-pool/nami/blob/vasil/build.zip
