### ISSUE TITLE
Send sundea token from exchange to wallet

### ISSUE THREAD

**Issue by Enterausername100** [berry-pool/nami#683]
Can you send sundea token from exchange to nami wallet?

**Comment by AdorchaDev** [comment]
Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

**Comment by Enterausername100** [comment]
It has been resolved by myself. Wen sending tokens on the caradano network from an exchange to your nami wallet. You need to add collateral. Which I did. And i recieved my tokens. 

Thanks for replying
