### ISSUE TITLE
Transaction fail when sending assets

### ISSUE THREAD

**Issue by jimbochewdip** [berry-pool/nami#710]
Nami wallet is working to make purchases on jpg.store and others, but when I try to send assets or ada from the wallet I get a transaction error.  Also, the ADA box is showing a red border before sending an nft with the auto populated amount.  Not sure what the reason for that is or if its related. Any ideas on what I'm doing wrong?

**Comment by Palumbochump** [comment]
I am having the same problem.

**Comment by MatinsDev** [comment]
@Palumbochump Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

**Comment by jimbochewdip** [comment]
It started working normally today again. Think an update to 3.3 was pushed on the relaunch or something.
