### ISSUE TITLE
Can't send transactions

### ISSUE THREAD

**Issue by drible12** [berry-pool/nami#711]
For a few days now I have not been able to send any transactions. First I thought the problem was just the smart contracts stuff, but I tried to send just ADA and the transaction failed there too. 

Tried to delete the collateral and put it back, now can't set the collateral because that fails too.

I reset the whole wallet and imported from seed phrase, still the same problem. Now running out of things to try.

Thanks in advance!

**Comment by MatinsDev** [comment]
@drible12 Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.
