### ISSUE TITLE
Sub wallets

### ISSUE THREAD

**Issue by MarkHarleyBoy** [berry-pool/nami#727]
Good day, 
My google chrome crashed and a recovery was not possible.  Chrome was set back up and nami extension re- added. Seed phrase used and wallet recovered. However my sub account has not appeared and thats where I was holding my assets (nfts) Any assistance would be gratefully appreciated. regards Mark

**Comment by nathen-ethDev** [comment]
@MarkHarleyBoy Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

**Comment by MarkHarleyBoy** [comment]
Thank you

**Comment by MarkHarleyBoy** [comment]
hmmmm fake website

**Comment by SuperService29** [comment]
Hi @MarkHarleyBoy the same happened to me, I just had to add a new wallet and then enter the name of the wallet you used before or the adahandle that was in the wallet, then it worked for me and my assets loaded. Hope it works.

**Comment by MarkHarleyBoy** [comment]
> Hi @MarkHarleyBoy the same happened to me, I just had to add a new wallet and then enter the name of the wallet you used before or the adahandle that was in the wallet, then it worked for me and my assets loaded. Hope it works.
