### ISSUE TITLE
Transaction history not showing after receiving ADA to payment part of address

### ISSUE THREAD

**Issue by rodrigomd94** [berry-pool/nami#739]
Today I sent some ADA to the payment part of my preprod address. Once the transaction went through I was not able to click on the "transaction history" button: the extension closes when I click. Balance seems to display correctly, and other accounts work without issues.

**Comment by KelvinEthDev** [comment]
@rodrigomd94 Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.
