### ISSUE TITLE
Transaction not possible (Can's send tokens)

### ISSUE THREAD

**Issue by kiruxaspb** [berry-pool/nami#793]
Hi. Faced with the problem of sending a large number of tokens from my address to another.

The wallet could not calculate the required amount of ADA to make a transaction for sending 20,000 test AGIX.
On the button only text: Transaction not possible

Here is the transaction:
https://preprod.cardanoscan.io/transaction/a3c768caa348f493f4861c5ff7e65ecc8ea46aac37da90e5128078a14fb11976

My attempts at matching ended up with me manually setting 3000 ADA, which is a lot for a transaction, and the change did not return.

Fortunately, I have such amounts in the preprod testnet, and if I don't have such an amount in the main network? Will I not be able to perform an action with my tokens in a similar situation?

Using wallet from Chrome Web Store.

**Comment by Kan-Eth** [comment]
@kiruxaspb Talk to Cardano Support on the [Live support page](https://explore-cardano.org) so that your issue can be looked into.

**Comment by Kan-Eth** [comment]
Have you have to resolved your issues? @kiruxaspb
