### ISSUE TITLE
checked runtime.lastError: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by choas** [berry-pool/nami#815]
When I try to connect (e.g. jpg.store) with Nami the inspect console shows this error: "checked runtime.lastError: Could not establish connection. Receiving end does not exist." ... and more.

After pressing the Nami connect button a second time the connection is established.

<img width="894" alt="Screenshot 2023-04-16 at 18 39 08" src="https://user-images.githubusercontent.com/138015/232327517-0046cff7-5f83-4bfc-8be0-84267b92e91f.png">

Note: I'm using Brave (shield up or down doesn't change the behavior) and this also happens on other sides.

**Comment by modeth** [comment]
@choas Talk to Cardano Support on the [Live support page](https://explore-cardano.com/) so that your issue can be looked into.

**Comment by alessandrokonrad** [comment]
I released a new version that fixes this. If you are on 3.4.7 you should be good. Just restart your browser to trigger the update.

**Comment by choas** [comment]
yes, 3.4.7 (after restarting the browser) works and no error message is shown in the console. Thank you!
