### ISSUE TITLE
Wallet not loading

### ISSUE THREAD

**Issue by nevcol** [berry-pool/nami#816]
<img width="420" alt="Screenshot 2023-04-16 at 10 03 07 PM" src="https://user-images.githubusercontent.com/98631015/232360851-ac5589fd-5c08-44dd-b575-3127acf67bdd.png">

My wallet for some reason does not want to load and show assets. I re started both my browser (brave) and computer a couple of times to see if those where the problems but when I open my wallet it keeps on looking as the picture. When I go on dapps if it connects it doesn't show balance, or I simply get a prompt stating that the wallet cannot be recognized.

I also verified on cardanoscan if maybe it was because my wallet was drained but my assests are all there.

**Comment by alessandrokonrad** [comment]
There is a new version 3.4.7 available that should fixed this again.

**Comment by Ophelia36** [comment]
Hi @nevcol   have this issue been resolved yet ? I suggest you contact wallet support developers on their web3chain website for assistance. [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance
