### ISSUE TITLE
IPFS caching / propagation time

### ISSUE THREAD

**Issue by kang-chen** [berry-pool/nami#817]
Hi, I've been testing some NFT mints with nami wallet on preview network and would like to understand how the IPFS caching is done.

I've uploaded a CID a few days ago and it's propagated, but seems to only appear in Nami wallet after a new request to a public node CID. This could well be an IPFS thing and nothing to do with Nami.

https://ipfs.io/ipfs/QmZmB64cq3yw5R3AM61seWaVWbsHyvuiHzg6cVJYs7crua

![Screen Shot 2023-04-21 at 12 09 33 pm](https://user-images.githubusercontent.com/6122370/233524089-5aa0d247-65d2-440f-ad04-b67806047e02.png)

The image in wallet will appear as blank if I do not make a cid request to a public node.

**Comment by kang-chen** [comment]
How do we get rid of scam users such as above, reporting to github? Do not click on the link

**Comment by ahymedDEV** [comment]
you can check the  [Issue 406](https://explore-cardano.com/)

**Comment by kang-chen** [comment]
closed as source code indicates it is blockfrost, therefore uploading to brockfrost IPFS API is the easiest way to ensure that the image appears as fast as possible
