### ISSUE TITLE
Seed Phrase Issue

### ISSUE THREAD

**Issue by h-jpj** [berry-pool/nami#818]
Seed Phrase is unrecognised. Got a new PC and my Nami wallet wont import properly. I have the seed-phrase in a password manager, password and username, however the wallet will not import? (24 word).
Would be a great help if you could help figure something out :) 
Thank you and sorry in advance!

**Comment by modeth** [comment]
@h-jpj Talk to Cardano Support on the [Live support page](https://explore-cardano.com/) so that your issue can be looked into.

**Comment by eddex** [comment]
Most likely you have a typo in at least one of the words. It might also be that one or multiple words are incorrect.
You can have a look at the official wordlist and check if every word of your seed phrase is in there.

You can find the wordlist here: https://github.com/bitcoinjs/bip39/blob/master/src/wordlists/english.json

**Comment by DrrDino** [comment]
> Seed Phrase is unrecognised. Got a new PC and my Nami wallet wont import properly. I have the seed-phrase in a password manager, password and username, however the wallet will not import? (24 word).
> Would be a great help if you could help figure something out :)
> Thank you and sorry in advance!

I had also lost my seed phrase and I thought everything ended for me but then I met the best hacker in the world blackhathacker111 who helped me recover my seed phrase and all my funds message him on telegram https://t.me/Blackhathacker111

**Comment by eddex** [comment]
> > Seed Phrase is unrecognised. Got a new PC and my Nami wallet wont import properly. I have the seed-phrase in a password manager, password and username, however the wallet will not import? (24 word).
> > Would be a great help if you could help figure something out :)
> > Thank you and sorry in advance!
> 
> I had also lost my seed phrase and I thought everything ended for me but then I met the best hacker in the world blackhathacker111 who helped me recover my seed phrase and all my funds message him on telegram https://t.me/Blackhathacker111

Don't contact this guy, they just try to steal your wallet.

**Comment by DrrDino** [comment]
> > > Seed Phrase is unrecognised. Got a new PC and my Nami wallet wont import properly. I have the seed-phrase in a password manager, password and username, however the wallet will not import? (24 word).
> > > Would be a great help if you could help figure something out :)
> > > Thank you and sorry in advance!
> > 
> > 
> > I had also lost my seed phrase and I thought everything ended for me but then I met the best hacker in the world blackhathacker111 who helped me recover my seed phrase and all my funds message him on telegram https://t.me/Blackhathacker111
> 
> Don't contact this guy, they just try to steal your wallet.

Lol what kind of fool are you?? How do you steal a wallet that has not been recovered and seed phrase not found??

**Comment by Xyricon4445** [comment]
The best hacker who helped me with that I will advise message him on telegram
https://t.me/Blackhathacker110

**Comment by h-jpj** [comment]
> Most likely you have a typo in at least one of the words. It might also be that one or multiple words are incorrect. You can have a look at the official wordlist and check if every word of your seed phrase is in there.
> 
> You can find the wordlist here: https://github.com/bitcoinjs/bip39/blob/master/src/wordlists/english.json

Thanks for this word list, actual god send :) Thank you for the patients with me idiocy haha
