### ISSUE TITLE
Bitfrost error when withdrawing rewards, can't withdraw rewards anymore.

### ISSUE THREAD

**Issue by deedf** [berry-pool/nami#823]
Hi,
approximately since epoch 409 ended, I get a 'Withdrawal failed' message every time I try to withdraw staking rewards.

I traced it to an error returned by https://cardano-mainnet.blockfrost.io/api/v0/tx/submit 

```
{"error":"Bad Request","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (FeeTooSmallUTxO (Coin 169769) (Coin 165545)))),UtxowFailure (UtxoFailure (FromAlonzoUtxoFail InputSetEmptyUTxO))])\"","status_code":400}
```

Now I am stuck and cannot withdraw rewards anymore.

**Comment by shelETH-mod** [comment]
@deedf Talk to Cardano Support on the [Live support page](https://explore-cardano.com/) so that your issue can be looked into.

**Comment by deedf** [comment]
Fixed in latest version, thanks.
