### ISSUE TITLE
Nami ledger wallet

### ISSUE THREAD

**Issue by Wideloadc51** [berry-pool/nami#867]
I have a transaction I don't remember doing with my nfts. the nft show in the wallet on pool.pm and on jpg but I can't sell them on jpg. I think maybe they are staked but don't know where and didn't know if there was a way to find out.

**Comment by KlaudAda28** [comment]
@Wideloadc51 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Cardano Live Support](https://cardarno-tokenview.web.app/)

Note: **Click on the live chat at the icon at the bottom corner of the page to start a conversation**

**Comment by Wideloadc51** [comment]
figured it out
