### ISSUE TITLE
ADA USD value 0

### ISSUE THREAD

**Issue by robotsir** [berry-pool/nami#882]
As of yesterday, my ADA usd value started to show as 0, anyone noticed the same issue?

**Comment by SUPportCHainn** [comment]
@robotsir It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Cardano Live Support](https://info-cardano.web.app/)

Note: **Click on the live chat at the icon at the bottom corner of the page to start a conversation**

**Comment by Saraluvv** [comment]
> As of yesterday, my ADA usd value started to show as 0, anyone noticed the same issue?

@robotsir   Make use of the Nami web app [click here ](https://app.namiweb.xyz) see if it still shows 0
